host: ""
port: 8317

auth-dir: "/root/.cli-proxy-api"

api-keys:
  - "sk-dummy"

debug: false

oauth-model-alias:
  codex:
    - name: "gpt-5.6-sol"
      alias: "gpt-5.6-sol-xhigh-fast"
      fork: true
    - name: "gpt-5.6-sol"
      alias: "gpt-5.6-sol-high-fast"
      fork: true
    - name: "gpt-5.6-luna"
      alias: "gpt-5.6-luna-xhigh-fast"
      fork: true
    - name: "gpt-5.6-luna"
      alias: "gpt-5.6-luna-high-fast"
      fork: true
    - name: "gpt-5.6-luna"
      alias: "gpt-5.6-luna-max-fast"
      fork: true
    - name: "gpt-5.6-luna"
      alias: "gpt-5.6-luna-medium-fast"
      fork: true
    - name: "gpt-5.6-luna"
      alias: "gpt-5.6-luna-low-fast"
      fork: true
payload:
  override:
    - models:
        - name: "gpt-5.6-sol-xhigh-fast"
          protocol: "codex"
      params:
        service_tier: "priority"
        reasoning.effort: "xhigh"
    - models:
        - name: "gpt-5.6-sol-high-fast"
          protocol: "codex"
      params:
        service_tier: "priority"
        reasoning.effort: "high"
    - models:
        - name: "gpt-5.6-luna-xhigh-fast"
          protocol: "codex"
      params:
        service_tier: "priority"
        reasoning.effort: "xhigh"
    - models:
        - name: "gpt-5.6-luna-high-fast"
          protocol: "codex"
      params:
        service_tier: "priority"
        reasoning.effort: "high"
    - models:
        - name: "gpt-5.6-luna-max-fast"
          protocol: "codex"
      params:
        service_tier: "priority"
        reasoning.effort: "max"
    - models:
        - name: "gpt-5.6-luna-medium-fast"
          protocol: "codex"
      params:
        service_tier: "priority"
        reasoning.effort: "medium"
    - models:
        - name: "gpt-5.6-luna-low-fast"
          protocol: "codex"
      params:
        service_tier: "priority"
        reasoning.effort: "low"
